#!/bin/sh
# SPDX-License-Identifier: Apache-2.0
# Generate version info from git tag or commit hash.
# Called as an Xcode Run Script Build Phase before compilation.

set -e

OUTPUT_FILE="${SRCROOT}/nailed/GeneratedVersion.swift"

# Try exact tag first, fall back to short commit hash
VERSION=$(git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD)

cat > "$OUTPUT_FILE" << EOF
// SPDX-License-Identifier: Apache-2.0
// Auto-generated by scripts/generate-version.sh — do not edit manually.

enum AppVersion {
    static let version: String = "$VERSION"
}
EOF
